version: '3.8'

services:
  web:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    restart: always

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: meudb
      MYSQL_USER: pabloak
      MYSQL_PASSWORD: 123456
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
